sync with master site

diff --git a/bin/multicrop b/bin/multicrop
--- a/bin/multicrop
+++ b/bin/multicrop
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
-# Revised by Fred Weinhaus ...................... revised 1/14/2018
+# Revised by Fred Weinhaus ...................... revised 2/18/2021
 # Revised by Anthony Thyssen to add -b option ... revised 8/24/2010
-# Developed by Fred Weinhaus 1/30/2010 .......... revised 4/25/2015
+# Developed by Fred Weinhaus .............................1/30/2010
 #
 # ------------------------------------------------------------------------------
 # 
@@ -29,7 +29,7 @@
 ####
 #
 # USAGE: multicrop [-c coords] [-b bcolor] [-f fuzzval] [-g grid] [-d discard] 
-# [-p prune] [-u unrotate] [i innertrim] [-e extend] [-m mask] [-D density] 
+# [-p prune] [-u unrotate] [i innertrim] [-e extend] [-m mask] [-r resize] [-D density] 
 # infile outfile
 # USAGE: multicrop [-h or -help]
 # 
@@ -42,7 +42,7 @@
 #                            any valid IM color; default is to use option -c
 # -f          fuzzval        fuzz value for separating background color;
 #                            expressed as (integer) percent 0 to 100; 
-#                            default=0 (uniform color)
+#                            default=10 (0 is uniform color)
 # -g          grid           grid spacing in both x and y as percent of 
 #                            image width and height; used to locate images;
 #                            integer>0; default=10;
@@ -61,6 +61,8 @@
 # -m          mask           mask presentation method; choices are view, 
 #                            save (to file) or output mask only; default 
 #                            is none of the above, just output the images
+# -r          resize         resize percent to scale the image down; float>0;  
+#                            default is no resizing.
 # -D          density        density to use when reading a single page of a PDF; 
 #                            integer>0; default is no assigned density
 # 
@@ -99,8 +101,9 @@
 # 
 # -b bcolor ... BCOLOR is the background color to use for flood fill instead 
 # of extracting this color from the image. This is useful when an image has 
-# no borders with sub-images hard against the edges. Any valid IM color is 
-# allowed. The default is to use option -c.
+# no borders so that the sub-images are hard against the edges. The bcolor 
+# will be used to put a one pixel border around the image and coords will be 
+# set to 0,0. Any valid IM color is allowed. The default is to use option -c.
 # 
 # -f fuzzval ... FUZZVAL is the fuzz amount specified as an integer percent
 # value between 0 to 100 (without the % sign). The correct choice of fuzz
@@ -151,6 +154,11 @@
 # images, but the background can "eat" a little into the images so long as no 
 # full edge is lost or the images is split into multiple parts.
 # 
+# -r resize ... RESIZE amount in percent to scale the image down. Values are floats>0.  
+# The default is no resizing. This is useful to improve speed and floodfilling 
+# when you have a large image, especially if the background is grainy. Note: do not 
+# include the % symbol.
+#
 # -D density ... DENSITY to use when reading a single page of a PDF. Multipage pdf 
 # files are not permitted. Values are integers>0. The default is no assigned density.
 # 
@@ -176,6 +184,7 @@ extend=0				# extend the output crop on all sides
 mask=""					# view, save, output
 unrotate=1				# 1=deskew 2=unrotate
 innertrim="no"			# trim inside cropped area to orthogonal rectangle
+resize=""				# resize percent
 density=""				# density to use for input PDF
 debug="false"
 
@@ -223,7 +232,7 @@ if [ $# -eq 0 ]
 	echo ""
 	usage2
 	exit 0
-elif [ $# -gt 24 ]
+elif [ $# -gt 26 ]
 	then
 	errMsg "--- TOO MANY ARGUMENTS WERE PROVIDED ---"
 else
@@ -329,6 +338,16 @@ else
 				   mask=`echo "$1" | tr "[:upper:]" "[:lower:]"`
 				   [ "$mask" != "view" -a "$mask" != "save" -a "$mask" != "output"  ] && errMsg "--- MASK=$mask MUST BE EITHER VIEW, SAVE OR OUTPUT ---"
 				   ;;
+			-r)    # resize
+				   shift  # to get the next parameter
+				   # test if parameter starts with minus sign 
+				   errorMsg="--- INVALID RESIZE SPECIFICATION ---"
+				   checkMinus "$1"
+				   resize=`expr "$1" : '\([.0-9]*\)'`
+				   [ "$resize" = "" ] && errMsg "--- RESIZE=$resize MUST BE A NON-NEGATIVE FLOAT VALUE (with no sign) ---"
+				   testA=`echo "$resize == 0" | bc`
+				   [ $testA -eq 1 ] && errMsg "--- RESIZE=$resize MUST BE A NON-NEGATIVE FLOAT VALUE GREATER THAN 0 ---"
+				   ;;
 			-D)    # density
 				   shift  # to get the next parameter
 				   # test if parameter starts with minus sign 
@@ -357,9 +376,9 @@ else
 fi
 
 # test if both bcolor and coords specified at the same time
-if [ "X$bcolor" != "X" -a "X$coords" != "X" ]; then
+if [ "$bcolor" != "" -a "$coords" != "" ]; then
   errMsg "--- BACKGROUND COLOR AND COODINATES CAN NOT BE USED TOGETHER ---"
-elif [ "X$bcolor" = "X" -a "X$coords" = "X" ]; then
+elif [ "$bcolor" = "" -a "$coords" = "" ]; then
 	coords="0,0"
 fi
 
@@ -390,19 +409,27 @@ tmpB3="$dir/multicrop_3_$$.cache"
 tmpA4="$dir/multicrop_4_$$.mpc"
 tmpB4="$dir/multicrop_4_$$.cache"
 tmpA5="$dir/multicrop_5_$$.miff"
+tmpA6="$dir/multicrop_6_$$.mpc"
+tmpB6="$dir/multicrop_6_$$.cache"
 
-trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5;" 0
-trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5; exit 1" 1 2 3 15
+trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5 $tmpB6 $tmpA6;" 0
+trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5 $tmpB6 $tmpA6; exit 1" 1 2 3 15
 #trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5; exit 1" ERR
 
 # read the input image into the temp files and test validity.
-convert -quiet $dproc "$infile" +repage "$tmpA1" ||
-	errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+if [ "$resize" != "" ]; then
+	convert -quiet $dproc "$infile" +repage "$tmpA6" ||
+		errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+	convert "$tmpA6" -resize $resize% "$tmpA1"
+else
+	convert -quiet $dproc "$infile" +repage "$tmpA1" ||
+		errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+fi
 
 
 # get im_version
 im_version=`convert -list configure | \
-	sed '/^LIB_VERSION_NUMBER /!d; s//,/;  s/,/,0/g;  s/,0*\([0-9][0-9]\)/\1/g' | head -n 1`
+	sed '/^LIB_VERSION_NUMBER */!d; s//,/;  s/,/,0/g;  s/,0*\([0-9][0-9]\)/\1/g' | head -n 1`
 
 # get output filename and suffix
 outnameArr=(`echo "$outfile" | sed -n 's/^\(.*\)[.]\([^.]*\)$/\1 \2/p'`)
@@ -427,10 +454,29 @@ test=`convert xc: -format "%[fx:$extend>0?1:0]" info:`
 [ $test -eq 1 -a $unrotate -eq 3 -a "$innertrim" = "yes" ] && errMsg "--- SIGN FOR EXTEND=$extend MUST BE NEGATIVE ---"
 
 
+# test if coords provided as x,y
+# coords="" if test fails and have other characters such as northwest
+coords1=`expr "$coords" : '\([0-9]*,[0-9]*\)'`
+
 # get color at user specified location
-if [ "X$bcolor" != "X" ]; then
+if [ "$bcolor" != "" ]; then
 	coords="0,0"
-else
+elif [ "$coords1" != "" -a "$resize" != "" ]; then
+	x=`echo "$coords1" | cut -d, -f1`
+	y=`echo "$coords1" | cut -d, -f2`
+	x=`convert xc: -format "%[fx:round($x*$resize/100)]" info:`
+	y=`convert xc: -format "%[fx:round($y*$resize/100)]" info:`
+	coords="$x,$y"
+	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
+elif [ "$coords1" != "" -a "$resize" = "" ]; then
+	x=`echo "$coords1" | cut -d, -f1`
+	y=`echo "$coords1" | cut -d, -f2`
+	# account for pad of 1
+	x=$((x+1))	
+	y=$((y+1))	
+	coords="$x,$y"
+	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
+elif [ "$coords1" = "" ]; then
 	widthm1=`convert xc: -format "%[fx:$width-1]" info:`
 	heightm1=`convert xc: -format "%[fx:$height-1]" info:`
 	midwidth=`convert xc: -format "%[fx:round(($width-1))/2]" info:`
@@ -445,7 +491,6 @@ else
 		s|south)         coords="$midwidth,$heightm1" ;;
 		sw|southwest)    coords="0,$heightm1" ;;
 		w|west)          coords="0,$midheight" ;;
-		[0-9]*,[0-9]*)   coords=$coords ;;
 		*)  errMsg "--- INVALID COORDS ---" ;;
 	esac
 	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
@@ -454,8 +499,8 @@ fi
 
 
 # get grid spacing
-wg=`convert xc: -format "%[fx:round($grid*$width/100)]" info:`
-hg=`convert xc: -format "%[fx:round($grid*$height/100)]" info:`
+wg=`convert xc: -format "%[fx:round(($grid/100)*$width)]" info:`
+hg=`convert xc: -format "%[fx:round(($grid/100)*$height)]" info:`
 num=`convert xc: -format "%[fx:round(100/$grid) - 2]" info:`
 #echo "width=$width; height=$height; wg=$wg; hg=$hg; num=$num"
 
@@ -542,77 +587,11 @@ for ((j=0;j<=$num;j++))
 			pg=`$identifying -ping -format "%g" $tmpA4`
 			offx=`echo $pg | cut -d+ -f2`
 			offy=`echo $pg | cut -d+ -f3`
-#			echo "Size: ${wd}x${ht}"  
-#			echo "Page Geometry: $pg"
-#			echo "offx=$offx; offy=$offy;"
-			echo "Initial Crop Box: ${wd}x${ht}+${offx}+${offy}"
-			echo ""
-			# Composite the black and white mask onto the original scan.
-			# Then trim and deskew/unrotate to make the output.
-			if [ $unrotate -eq 3 ]; then
-				if [ $extend -eq 0 -o "$innertrim" = "yes" ]; then
-					convert $tmpA1 -crop ${wd}x${ht}+${offx}+${offy} +repage $tmpA5
-				elif [ "$innertrim" = "no" -a $extend -ne 0 ]; then
-					wd=$((wd+2*extend))
-					ht=$((ht+2*extend))
-					offx=$((offx-extend))
-					offy=$((offy-extend))
-					convert $tmpA1 -crop ${wd}x${ht}+${offx}+${offy} +repage $tmpA5
-				fi
-			elif [ $unrotate -eq 1 ]; then
-				convert $tmpA1 -crop ${wd}x${ht}+${offx}+${offy} +repage $derotate \
-					-bordercolor "$bcolor" -border 2 -fuzz ${fuzzval}% -trim +repage $tmpA5
-				if [ "$innertrim" = "no" -a $extend -ne 0 ]; then
-					wd=`$identifying -ping -format "%w" $tmpA5`
-					ht=`$identifying -ping -format "%h" $tmpA5`
-					wd=$((wd+2*extend))
-					ht=$((ht+2*extend))
-					offx=$((-extend))
-					offy=$((-extend))
-					convert $tmpA5 -crop ${wd}x${ht}+${offx}+${offy} +repage $tmpA5
-				fi
-			elif [ $unrotate -eq 2 ]; then
-				convert $tmpA1 -crop ${wd}x${ht}+${offx}+${offy} +repage  \
-					-fuzz ${fuzzval}% -trim +repage miff:- | \
-				unrotate -C "$bcolor" -f ${fuzzval}% - $tmpA5
-				if [ "$innertrim" = "no" -a $extend -ne 0 ]; then
-					wd=`$identifying -ping -format "%w" $tmpA5`
-					ht=`$identifying -ping -format "%h" $tmpA5`
-					wd=$((wd+2*extend))
-					ht=$((ht+2*extend))
-					offx=$((-extend))
-					offy=$((-extend))
-					convert $tmpA5 -crop ${wd}x${ht}+${offx}+${offy} +repage $tmpA5
-				fi
-			fi
-			if [ "$innertrim" = "yes" ]; then
-				mextend=-$extend
-				autotrim -m inner -f $fuzzval -C "$bcolor" -l $mextend -t $mextend \
-					-r $extend -b $extend $tmpA5 ${outname}-${kk}.${suffix}
-			else
-				convert $tmpA5 ${outname}-${kk}.${suffix}
-			fi
-
-			# Fill the selected photo area in the red/none mask with none 
-			# for use with next coordinate so that it does not find it again.
-			convert $tmpA3 -channel rgba -alpha on -fill none -opaque white $tmpA2
-			if [ "$discard" = "" ]; then
-				k=$(($k + 1))
-			elif [ $wd -lt $discard -o $ht -lt $discard ]; then 
-				rm -f ${outname}-${kk}.${suffix}
-				echo "Discarding Image $k"
-			else
-				k=$(($k + 1))
-			fi
-		fi
-	done
-done
-echo ""
-exit 0
-
-
-
-und($offy*100/$resize)-$extend]" info:`
+			if [ "$resize" != "" ]; then
+				wd=`convert xc: -format "%[fx:round($wd*100/$resize)+2*$extend]" info:`
+				ht=`convert xc: -format "%[fx:round($ht*100/$resize)+2*$extend]" info:`
+				offx=`convert xc: -format "%[fx:round($offx*100/$resize)-$extend]" info:`
+				offy=`convert xc: -format "%[fx:round($offy*100/$resize)-$extend]" info:`
 				img=$tmpA6
 			else
 				wd=$((wd+2*extend))
diff --git a/bin/tshirtwarp b/bin/tshirtwarp
--- a/bin/tshirtwarp
+++ b/bin/tshirtwarp
@@ -1,6 +1,6 @@
 #!/bin/bash
 # 
-# Developed by Fred Weinhaus 11/11/2014 .......... revised 8/28/2017
+# Developed by Fred Weinhaus 11/11/2014 .......... revised 7/17/2020
 #
 # ------------------------------------------------------------------------------
 # 
@@ -26,13 +26,16 @@
 # 
 ####
 #
-# USAGE: tshirtwarp lightingfile displacementfile infile backgroundfile outfile
+# USAGE: tshirtwarp lightingfile displacementfile infile backgroundfile [maskfile] outfile
 # or
-# USAGE: tshirtwarp datadirectory infile backgroundfile outfile
+# USAGE: tshirtwarp datadirectory infile backgroundfile [maskfile] outfile
 # 
 # infile is the image to be placed onto the tshirt
 # 
 # backgroundfile is the tshirt image
+# 
+# maskfile is an optional mask image to limit the placement of the overlay image 
+# on the tshirt.
 # 
 # lighting file and displacement file are generated by the script tshirt with 
 # the -E option.
@@ -72,27 +75,64 @@
 ######
 # 
 
-
 # get arguments
 numargs=$#
-if [ $# -eq 4 ]; then
-	# directory file specified, which contains all needed files
-	directory="$1"						# directory containing all needed images and text file
-	infile="$2"							# input image
-	bgfile="$3"							# optional background image or if no background image then output image
-	outfile="$4"						# output image
-	lfile="$directory/lighting.png"		# lighting image
-	dfile="$directory/displace.png"		# dispacement image
-	source $directory/tshirtdata.txt	# (source) reads and executes commands from given FILENAME and return
-
-elif [ $# -eq 5 ]; then
-	# no directory file specified and lighting and displacement files provided
-	lfile="$1"			# lighting image
-	dfile="$2"			# dispacement image
-	infile="$3"			# input image
-	bgfile="$4"			# background image
-	outfile="$5"		# output image
-
+maskfile=""
+# test if first argument a directory
+if [ -d "$1" -a ! -r "$1" ]; then
+	echo "--- DIRECTORY IS NOT READABLE ---"
+	exit 1
+fi
+if [ -d "$1" -a ! -s "$1" ]; then
+	echo "--- DIRECTORY IS EMPTY ---"
+	exit 1
+fi
+if [ -d "$1" -a -r "$1" -a -s "$1" ]; then
+	# directory exists, is readable and is not empty
+	if [ $# -eq 4 ]; then
+		# directory file specified, which contains all needed files
+		directory="$1"						# directory containing all needed images and text file
+		infile="$2"							# input image
+		bgfile="$3"							# background (tshirt) image
+		outfile="$4"						# output image
+		lfile="$directory/lighting.png"		# lighting image
+		dfile="$directory/displace.png"		# dispacement image
+		source $directory/tshirtdata.txt	# (source) reads and executes commands from given FILENAME and return
+	elif [ $# -eq 5 ]; then
+		# directory file specified, which contains all needed files
+		directory="$1"						# directory containing all needed images and text file
+		infile="$2"							# input image
+		bgfile="$3"							# background (tshirt) image
+		maskfile="$4"						# mask file
+		outfile="$5"						# output image
+		lfile="$directory/lighting.png"		# lighting image
+		dfile="$directory/displace.png"		# dispacement image
+		source $directory/tshirtdata.txt	# (source) reads and executes commands from given FILENAME and return
+	else
+		echo "--- INCONSISTENT NUMBER OF INPUT AND OUTPUT IMAGES SPECIFIED ---"
+		exit 1
+	fi
+else
+	if [ $# -eq 5 ]; then
+		# no directory file specified and lighting and displacement files provided
+		lfile="$1"			# lighting image
+		dfile="$2"			# dispacement image
+		infile="$3"			# input image
+		bgfile="$4"			# background image
+		outfile="$5"		# output image
+	elif [ $# -eq 6 ]; then
+		# no directory file specified and lighting and displacement files provided
+		lfile="$1"			# lighting image
+		dfile="$2"			# dispacement image
+		infile="$3"			# input image
+		maskfile="$4"		# mask file
+		bgfile="$5"			# background image
+		outfile="$6"		# output image
+	else
+		echo "--- INCONSISTENT NUMBER OF INPUT AND OUTPUT IMAGES SPECIFIED ---"
+		exit 1
+	fi
+fi
 	
 #### -------------------------------------------------------------------------------------
 #### SET INTERNAL ARGUMENTS HERE (PASTED FROM THE OUTPUT OF TSHIRT SCRIPT TO THE TERMINAL)
@@ -104,12 +144,6 @@ elif [ $# -eq 5 ]; then
 
 #### END INTERNAL ARGUMENTS
 #### -------------------------------------------------------------------------------------
-
-
-else
-	echo "INCORRECT NUMBER OF FILES SPECIFIED"
-	exit 1
-fi
 
 
 # test that lfile provided
@@ -154,7 +188,6 @@ trap "rm -rf $dir;" 0
 trap "rm -rf $dir; exit 1" 1 2 3 10 15
 trap "rm -rf $dir; exit 1" ERR
 
-
 # read lfile image
 if ! convert -quiet "$lfile" +repage $dir/tmpL.miff; then
 	echo "--- FILE $lfile DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE ---"
@@ -173,14 +206,21 @@ if ! convert -quiet "$infile" +repage $modulating $dir/tmpI.miff; then
 	exit 1
 fi	
 
-# read bgfile (tshirt) image
-if ! convert -quiet "$bgfile" +repage $dir/tmpT.miff; then
+# read bgfile (tshirt) image and make color (so that result is not grayscale when overlay image is grayscale)
+if ! convert -quiet "$bgfile" +repage -colorspace sRGB $dir/tmpT.miff; then
 	echo "--- FILE $infile DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE ---"
 	exit 1
 fi	
 
+if [ "$maskfile" != "" ]; then
+	# read maskfile image
+	if ! convert -quiet "$maskfile" +repage $dir/tmpM.miff; then
+		echo "--- FILE $maskfile DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE ---"
+	fi	
+fi
+
 im_version=`convert -list configure | \
-	sed '/^LIB_VERSION_NUMBER /!d; s//,/;  s/,/,0/g;  s/,0*\([0-9][0-9]\)/\1/g' | head -n 1`
+	sed '/^LIB_VERSION_NUMBER */!d; s//,/;  s/,/,0/g;  s/,0*\([0-9][0-9]\)/\1/g' | head -n 1`
 
 if [ "$im_version" -ge "07000000" ]; then
 	identifying="magick identify"
@@ -188,6 +228,137 @@ else
 	identifying="identify"
 fi
 
+# get tshirt region corner coordinates and separate into x,y values
+# tshirt coordinates are the even elements in coordinates
+# overlay coordinates are the odd elements in the array
+# re-compute overlay image coordinates below
+ptArr=($coordinates)
+num_pts=${#ptArr[*]}
+if [ $num_pts -ne 8 ]; then 
+	echo "--- INVALID NUMBER OF COORDINATES ---"
+	exit 1
+fi
+for ((i=0; i<4; i++)); do
+	j=$((2*i+1))
+	xptArr[$i]=`echo ${ptArr[$j]} | cut -d, -f1`
+	yptArr[$i]=`echo ${ptArr[$j]} | cut -d, -f2`
+done
+
+x1=${xptArr[0]}
+y1=${yptArr[0]}
+x2=${xptArr[1]}
+y2=${yptArr[1]}
+x3=${xptArr[2]}
+y3=${yptArr[2]}
+x4=${xptArr[3]}
+y4=${yptArr[3]}
+#echo "$x1,$y1 $x2,$y2 $x3,$y3 $x4,$y4"
+
+# get width and height of overlay image and compute scale factor to fit region
+ww=`convert -ping $dir/tmpI.miff -format "%w" info:`
+hh=`convert -ping $dir/tmpI.miff -format "%h" info:`
+# distort does not need scale to be computed. Perspective distort will do that.
+if [ "$fit" = "scale" ]; then
+	if [ $hh -ge $ww ]; then
+		scale=`convert xc: -format "%[fx:($hh-1)/($leftheight-1)]" info:`
+	else
+		scale=`convert xc: -format "%[fx:($ww-1)/($topwidth-1)]" info:`
+	fi
+elif [ "$fit" = "top" ]; then
+	xscale=`convert xc: -format "%[fx:($ww-1)/($topwidth-1)]" info:`
+	yscale=`convert xc: -format "%[fx:($hh-1)/($leftheight-1)]" info:`
+	scale=`convert xc: -format "%[fx:$xscale>$yscale?$xscale:$yscale]" info:`
+	scaleflag=`convert xc: -format "%[fx:$xscale>$yscale?1:0]" info:`
+	[ $scaleflag -eq 1 ] && scaleflag="x" || scaleflag="y"
+elif [ "$fit" = "crop" -o "$fit" = "none" ]; then
+	scale=`convert xc: -format "%[fx:($ww-1)/($topwidth-1)]" info:`
+fi
+#echo "scale=$scale; ww=$ww; hh=$hh;"
+
+# compute overlay image coordinates from tshirt coordinates and fit and scale
+# subtract offset and unrotate
+# xoffset and yoffset are likely 0?
+xoffset=0
+yoffset=0
+xo1=`convert xc: -format "%[fx:round(($x1-$xoffset)*cos($angle)+($y1-$yoffset)*sin($angle))]" info:`
+yo1=`convert xc: -format "%[fx:round(($x1-$xoffset)*sin($angle)+($y1-$yoffset)*cos($angle))]" info:`
+xo2=`convert xc: -format "%[fx:round(($x2-$xoffset)*cos($angle)+($y2-$yoffset)*sin($angle))]" info:`
+yo2=`convert xc: -format "%[fx:round(($x2-$xoffset)*sin($angle)+($y2-$yoffset)*cos($angle))]" info:`
+xo3=`convert xc: -format "%[fx:round(($x3-$xoffset)*cos($angle)+($y3-$yoffset)*sin($angle))]" info:`
+yo3=`convert xc: -format "%[fx:round(($x3-$xoffset)*sin($angle)+($y3-$yoffset)*cos($angle))]" info:`
+xo4=`convert xc: -format "%[fx:round(($x4-$xoffset)*cos($angle)+($y4-$yoffset)*sin($angle))]" info:`
+yo4=`convert xc: -format "%[fx:round(($x4-$xoffset)*sin($angle)+($y4-$yoffset)*cos($angle))]" info:`
+# compute max width and height
+# error fixed below 3/19/2020 wo=`convert xc: -format "%[fx:max($xo4-$xo1,$xo3-$xo2)+1]" info:`
+wo=`convert xc: -format "%[fx:max($xo2-$xo1,$xo4-$xo3)+1]" info:`
+ho=`convert xc: -format "%[fx:max($yo4-$yo1,$yo3-$yo2)+1]" info:`
+#echo "xoffset=$xoffset; yoffset=$yoffset; angle=$angle; wo=$wo; ho=$ho;"
+if [ "$fit" = "distort" ]; then
+	xo1=0
+	yo1=0
+	xo2=$((ww-1))
+	yo2=$yo1
+	xo3=$xo2
+	yo3=$((hh-1))
+	xo4=$xo1
+	yo4=$yo3
+elif [ "$fit" = "scale" ]; then
+	if [ $hh -ge $ww ]; then
+		xo1=`convert xc: -format "%[fx:round(0.5*($ww-$scale*$wo))]" info:`
+		yo1=0
+		xo2=`convert xc: -format "%[fx:(round($xo1+$scale*$wo-1))]" info:`
+		yo2=$yo1
+		xo3=$xo2
+		yo3=`convert xc: -format "%[fx:(round($yo1+$scale*$ho-1))]" info:`
+		xo4=$xo1
+		yo4=$yo3
+	else
+		xo1=0
+		yo1=`convert xc: -format "%[fx:round(0.5*($hh-$scale*$ho))]" info:`
+		xo2=`convert xc: -format "%[fx:(round($xo1+$scale*$wo-1))]" info:`
+		yo2=$yo1
+		xo3=$xo2
+		yo3=`convert xc: -format "%[fx:(round($yo1+$scale*$ho-1))]" info:`
+		xo4=$xo1
+		yo4=$yo3
+	fi
+	elif [ "$fit" = "top" ]; then
+		if [ "$scaleflag" = "y" ]; then
+			xo1=`convert xc: -format "%[fx:round(0.5*($ww-$scale*$wo))]" info:`
+			yo1=0
+			xo2=`convert xc: -format "%[fx:(round($xo1+$scale*$wo-1))]" info:`
+			yo2=$yo1
+			xo3=$xo2
+			yo3=`convert xc: -format "%[fx:(round($yo1+$scale*$ho-1))]" info:`
+			xo4=$xo1
+			yo4=$yo3
+		else
+			xo1=0
+			# center
+			#yo1=`convert xc: -format "%[fx:round(0.5*($hh-$scale*$ht))]" info:`
+			yo1=0
+			xo2=`convert xc: -format "%[fx:(round($xo1+$scale*$wo-1))]" info:`
+			yo2=$yo1
+			xo3=$xo2
+			yo3=`convert xc: -format "%[fx:(round($yo1+$scale*$ho-1))]" info:`
+			xo4=$xo1
+			yo4=$yo3
+		fi
+elif [ "$fit" = "crop" -o "$fit" = "none" ]; then
+	xo1=0
+	yo1=0
+	xo2=$((ww-1))
+	yo2=$yo1
+	xo3=$xo2
+	yo3=`convert xc: -format "%[fx:(round($scale*$ho-1))]" info:`
+	xo4=$xo1
+	yo4=$yo3
+fi
+#echo "$xo1,$yo1;  $xo2,$yo2;  $xo3,$yo3;  $xo4,$yo4;"
+
+# define coordinate pairs for perspective transform
+coordinates="$xo1,$yo1 $x1,$y1 $xo2,$yo2 $x2,$y2 $xo3,$yo3 $x3,$y3 $xo4,$yo4 $x4,$y4"
+#echo "$coordinates"
 
 # test if tshirt/bgfile has alpha. If so remove and save for later.
 is_alpha=`$identifying -verbose $bgfile | grep "Alpha" | head -n 1`
@@ -208,9 +379,22 @@ else
 	swapping=""
 fi
 
+# set up for opacity
+if [ "$opacity" != "100" ]; then
+	opacity=`convert xc: -format "%[fx:$opacity/100]" info:`
+	oproc="-alpha on -channel a -evaluate multiply $opacity +channel"
+else
+	oproc=""
+fi
+
+
+if [ "$maskfile" != "" ]; then
+	mask="$dir/tmpM.miff"
+else
+	mask=""
+fi
 
 # process image
-
 if [ "$is_alpha" != "" ]; then
 	# line2 1-3:   process overlay image to perspective transform with transparent
 	#              background the size of the tshirt image and sharpen
@@ -220,18 +404,19 @@ if [ "$is_alpha" != "" ]; then
 	#              and add back alpha channel
 	# note: IM 7 needs -respect-parenthesis to that -compose copy_opacity following tmpL works properly, 
 	# but IM 6 does not.
-	convert -respect-parenthesis \( $dir/tmpT.miff -alpha transparent \) \
+	# note: need to add -colorspace sRGB to tmpTG to keep tmpI as color after layers merge 7/17/2020 some time after 7.0.8.23
+	convert -respect-parenthesis \( $dir/tmpT.miff -alpha transparent -colorspace sRGB \) \
 		\( $dir/tmpI.miff -virtual-pixel none +distort perspective "$coordinates" $sproc \) \
 		-background none -layers merge +repage \
 		\
 		\( -clone 0 -alpha extract \) \
-		\( -clone 0 $dir/tmpL.miff $swapping -compose $compose -composite \) \
+		\( -clone 0 $oproc \( $dir/tmpL.miff \) $swapping -alpha off -compose $compose -composite \) \
 		-delete 0 +swap -compose over -alpha off -compose copy_opacity -composite \
 		\
 		$dir/tmpD.miff \
 		-define compose:args=-$displace,-$displace -compose displace -composite \
 		\
-		$dir/tmpT.miff +swap -compose over -composite \
+		$dir/tmpT.miff +swap $mask -compose over -composite \
 		$dir/tmpA.miff -alpha off -compose copy_opacity -composite "$outfile"
 
 else
@@ -245,22 +430,13 @@ else
 		-background none -layers merge +repage \
 		\
 		\( -clone 0 -alpha extract \) \
-		\( -clone 0 $dir/tmpL.miff $swapping -compose $compose -composite \) \
+		\( -clone 0 $oproc \( $dir/tmpL.miff \) $swapping -compose $compose -composite \) \
 		-delete 0 +swap -compose over -alpha off -compose copy_opacity -composite \
 		\
 		$dir/tmpD.miff \
 		-define compose:args=-$displace,-$displace -compose displace -composite \
 		\
-		$dir/tmpT.miff +swap -compose over -composite "$outfile"
-fi
-
-exit 0
-r -alpha off -compose copy_opacity -composite \
-		\
-		$dir/tmpD.miff \
-		-define compose:args=-$displace,-$displace -compose displace -composite \
-		\
-		$dir/tmpT.miff +swap -compose over -composite "$outfile"
+		$dir/tmpT.miff +swap $mask -compose over -composite "$outfile"
 fi
 
 exit 0
